---
abstract: 'Installs the main set of Email:: modules'
author:
  - 'Ricardo SIGNES <rjbs@cpan.org>'
build_requires:
  File::Spec: 0.82
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bundle-Email
no_index:
  directory:
    - inc
    - t
requires:
  Email::Abstract: 0
  Email::Address: 0
  Email::Date: 0
  Email::Folder: 0
  Email::FolderType: 0
  Email::FolderType::Net: 0
  Email::LocalDelivery: 0
  Email::MIME: 0
  Email::MIME::ContentType: 0
  Email::MIME::Creator: 0
  Email::MIME::Encodings: 0
  Email::MIME::Modifier: 0
  Email::MessageID: 0
  Email::Send: 0
  Email::Send::Test: 0
  Email::Simple: 0
  Email::Simple::Creator: 0
  Email::Stuff: 0
  File::Slurp: 0
  File::Type: 0
  Module::Pluggable: 0
  Net::SMTP: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rjbs/bundle-email
version: 0.044
